server:
  port: 9002
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.6.152:9200
logging:
  level:
    tracer: trace
#    com.atguigu.gmall: trace
    org.elasticsearch: trace