server:
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  zipkin:
#    base-url: http://192.168.6.152:9411/
#    sender:
#      type: web
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
