#
spring:
  shardingsphere:
    datasource:
      names: master,slave_01,slave_02

      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        # http://192.168.200.1:8888/aaaa?a=b&c=d
        jdbcUrl: jdbc:mysql://192.168.6.152:3306/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      slave_01:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        # http://192.168.200.1:8888/aaaa?a=b&c=d
        jdbcUrl: jdbc:mysql://192.168.6.152:3307/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      slave_02:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        # http://192.168.200.1:8888/aaaa?a=b&c=d
        jdbcUrl: jdbc:mysql://192.168.6.152:3308/gmall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456


    rules:
      readwrite-splitting:
        data-sources:
          myds:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave_01,slave_02
            load-balancer-name: rb


        load-balancers:
          rb:
            type: ROUND_ROBIN



    props:
      sql-show: true


